"use client"

import { createContext, useContext, useState, useEffect, ReactNode } from "react"

const translations = {
  en: {
    // Sidebar & Navigation
    dashboard: "Dashboard",
    bmiCalculator: "BMI Calculator",
    calories: "Meals & Calories",
    journey: "15-Day Journey",
    cycle: "Cycle Tracker",
    chat: "AI Nutritionist",
    aiChat: "AI Nutritionist",
    wellness: "Healthy Reads",
    doctors: "Doctors",
    profile: "Profile",
    settings: "Settings",
    logout: "Logout",

    // Header & User dropdown
    profile2: "Profile",
    settings2: "Settings",
    logout2: "Logout",

    // Greetings & Dashboard
    greetingMorning: "Good morning",
    greetingAfternoon: "Good afternoon",
    greetingEvening: "Good evening",
    hereIsYourHealth: "Here is your health summary today 💗",
    yourBMI: "Your BMI",
    dailyCalories: "Daily Calories",
    waterIntake: "Water Intake",
    glasses: "glasses",
    kcal: "kcal",
    recommended: "Target",
    weeklyActivity: "Hydration History",
    waterConsumption: "Daily water consumption (glasses)",
    healthOverview: "Health Overview",
    healthOverviewDesc: "You are maintaining healthy balance. Keep it up!",
    viewDetails: "View 15-Day Progress",
    aiDailyTip: "AI Daily Insight",
    hydrate: "Hydrate!",
    good: "Good",
    perfect: "Perfect!",
    overhydrated: "Well Hydrated!",
    calculateYourBMI: "Calculate your BMI to start tracking",
    setCalorieTarget: "Set your daily calorie target",
    quickActions: "Quick Actions",
    logMeal: "Log Meal",
    addWater: "Add Water",
    logWeight: "Log Weight",
    askAI: "Ask AI",
    consumed: "Consumed",
    target: "Target",
    remaining: "Remaining",
    startTrackingToday: "Start tracking today to build your 15-day journey.",

    // Meals & Calories Page
    mealLog: "Daily Meal Log",
    calorieCalculator: "Calorie Calculator",
    calorieTitle: "Meal & Calorie Tracking",
    calorieSubtitle: "Track meals, calculate targets & get AI nutrition breakdowns",
    noMealsLoggedToday: "No meals logged yet today.",
    dontKnowCalories: "Don't know the calories? Ask AI",
    addMealBtn: "+ Add Meal",
    foodName: "Food Name",
    quantity: "Quantity / Portion",
    estimatedCalories: "Estimated Calories",
    protein: "Protein (g)",
    carbs: "Carbs (g)",
    fat: "Fat (g)",
    mealType: "Meal Type",
    breakfast: "Breakfast",
    lunch: "Lunch",
    dinner: "Dinner",
    snack: "Snacks",
    saveMeal: "Save Meal",
    deleteMeal: "Delete",
    saveTargetBtn: "Save Daily Target",
    enterDetails: "Enter Details",
    age: "Age",
    gender: "Gender",
    selectGender: "Select gender",
    male: "Male",
    female: "Female",
    others: "Others",
    activityLevel: "Activity Level",
    selectActivity: "Select activity level",
    sedentary: "Sedentary (little to no exercise)",
    light: "Light (1-3 days/week)",
    moderate: "Moderate (3-5 days/week)",
    active: "Active (6-7 days/week)",
    veryActive: "Very Active (intense exercise)",
    goal: "Your Health Goal",
    loseWeight: "Lose Weight",
    maintainWeight: "Maintain Weight",
    gainWeight: "Gain Weight",
    estimatedDailyNeeds: "Estimated Daily Calorie Needs",
    bmr: "Basal Metabolic Rate (BMR)",
    tdee: "Estimated Maintenance (TDEE)",
    calorieDisclaimer: "Estimated daily calorie needs based on standard Mifflin-St Jeor guidelines. Actual needs may vary.",

    // BMI Page
    bmiTitle: "BMI Calculator",
    bmiSubtitle: "Screen your Body Mass Index with personalized insights",
    enterYourDetails: "Enter Your Details",
    heightWeightForBMI: "Height and weight for BMI calculation",
    heightCm: "Height (cm)",
    weightKg: "Weight (kg)",
    calculateBMI: "Calculate BMI",
    saveToProfile: "Save to Profile & Dashboard",
    bmiCategories: "BMI Categories",
    underweight: "Underweight",
    normal: "Normal",
    overweight: "Overweight",
    obese: "Obese",
    yourBMIResult: "Your BMI Result",
    aiSuggestion: "AI Wellness Suggestion",
    maintainBalanced: "Maintain a balanced diet and exercise regularly.",
    underweightSuggestion: "You are underweight. Consider nutrient-rich foods with healthy calories and protein.",
    normalSuggestion: "You are in a healthy range! Maintain a balanced diet and regular physical activity.",
    overweightSuggestion: "Focus on mindful eating, whole foods, and 30 minutes of daily activity.",
    obeseSuggestion: "Prioritize consistent balanced nutrition, hydration, and consultation with a healthcare professional.",
    bmiDisclaimer: "BMI is a screening measure and does not directly measure body fat, muscle distribution, or overall health.",

    // AI Chat
    chatTitle: "AI Nutrition Companion",
    chatSubtitle: "Intelligent food analysis, meal breakdowns & dietary advice",
    chatPlaceholder: "Ask about a recipe, type food items or upload photo...",
    isHealthy: "Is this healthy?",
    estimateCaloriesChip: "Estimate calories",
    nutritionTips: "Nutrition tips",
    saveToCalorieLog: "Save to Calorie Log",
    imageLoaded: "Image Loaded",
    readyForAnalysis: "Ready for nutritional scan...",
    scanningMeal: "Scanning Meal with AI...",
    aiEstimatedNotice: "Estimated calories. Actual values depend on portion, ingredients and preparation.",

    // 15-Day Health Journey
    journeyTitle: "My Health Journey",
    journeySubtitle: "Your rolling 15 days of health & wellness progress.",
    startingWeight: "Starting Weight",
    currentWeight: "Current Weight",
    goalWeight: "Goal Weight",
    weightChange: "Weight Change",
    avgCalories: "Avg Calories",
    avgWater: "Avg Water",
    weightTrend: "Weight Trend (kg)",
    calorieTrend: "Calories Consumed vs Target",
    waterTrend: "Water Intake (glasses)",
    goalProgress: "Goal Progress",
    logNewWeight: "+ Log New Weight",

    // Women's Cycle Tracker
    cycleTitle: "Women's Health & Cycle Tracker",
    cycleSubtitle: "Gentle predictive cycle insights & personalized wellness guidance.",
    periodStartedToday: "Period Started Today 🩸",
    currentPhase: "Current Phase",
    cycleDay: "Cycle Day",
    estimatedNextPeriod: "Estimated Next Period",
    estimatedFertileWindow: "Estimated Fertile Window",
    estimatedOvulation: "Estimated Ovulation",
    menstrualPhase: "Menstrual Phase",
    follicularPhase: "Follicular Phase",
    ovulationPhase: "Ovulation Phase",
    lutealPhase: "Luteal Phase",
    cycleDisclaimer: "All cycle and fertility dates are estimates based on standard rhythm calendars and are not medical or contraceptive guarantees.",
    cycleNutritionTips: "Phase Nutrition Tips",

    // Nutrition & Wellness Library
    wellnessTitle: "Nutrition & Wellness Reads",
    wellnessSubtitle: "Evidence-backed diet plans, practical meal ideas & lifestyle guides",
    dietPlansTab: "Diet Plans",
    mealIdeasTab: "Meal Ideas",
    articlesTab: "Wellness Guides",
    readGuide: "Read Guide",

    // Profile Page
    profileTitle: "Profile & Wellness",
    profileSubtitle: "Manage your personal health information",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    healthInformation: "Health Metrics",
    height: "Height",
    weight: "Weight",
    bloodType: "Blood Group",
    city: "City / Location",
    namePlaceholder: "Enter your name",
    emailPlaceholder: "Your email",
    phonePlaceholder: "Enter phone number",
    locationPlaceholder: "Enter your city",

    // Settings Page
    settingsTitle: "Settings",
    settingsSubtitle: "Manage your application preferences",
    preferences: "Preferences",
    darkMode: "Dark Mode",
    darkModeDesc: "Switch between light and dark themes",
    language: "Language",
    languageDesc: "English (US)",
    change: "Change",
    security: "Security",
    changePassword: "Change Password",
    dangerZone: "Danger Zone",
    dangerZoneDesc: "Once you delete your account, there is no going back. Please be certain.",
    deleteAccount: "Delete Account",
    changePasswordTitle: "Change Password",
    changePasswordSubtitle: "Update your account password",
    currentPassword: "Current Password",
    currentPasswordPlaceholder: "Enter current password",
    newPassword: "New Password",
    newPasswordPlaceholder: "Enter new password (min. 6 characters)",
    confirmPassword: "Confirm New Password",
    confirmPasswordPlaceholder: "Re-enter new password",
    updatePasswordBtn: "Update Password",
    updating: "Updating...",
    cancel: "Cancel",
    passwordUpdatedSuccess: "Password updated successfully!",
    deleteConfirmTitle: "Delete Account Permanently?",
    deleteConfirmDesc: "This action is permanent. Your profile, health metrics, and meal history will be erased.",
    deleteConfirmPrompt: "Please enter your password to confirm:",
    deletePasswordPlaceholder: "Enter your password to confirm",
    confirmDeleteBtn: "Permanently Delete Account",
    deleting: "Deleting...",

    // Errors & Auth
    userNotFound: "No authenticated user found.",
    notPasswordUser: "Password change is only available for email/password accounts.",
    enterCurrentPassword: "Please enter your current password.",
    passwordTooShort: "New password must be at least 6 characters.",
    passwordsDoNotMatch: "New passwords do not match.",
    wrongPassword: "The password entered is incorrect.",
    recentLoginRequired: "This action requires recent authentication. Please verify your current password.",
    tooManyAttempts: "Too many attempts. Please try again later.",
    welcomeBack: "Welcome Back",
    signInToContinue: "Sign in to continue your health journey",
    rememberMe: "Remember me",
    forgotPassword: "Forgot Password?",
    login: "Login",
    orContinueWith: "or continue with",
    noAccount: "Don't have an account?",
    signUp: "Sign up",
    createAccount: "Create Account",
    joinHealthJourney: "Join your health journey today",
    fullName: "Full Name",
    orSignUpWith: "or sign up with",
    alreadyHaveAccount: "Already have an account?",
    agreeToTerms: "I agree to the Terms & Conditions",
    viewProfile: "View Profile",
    doctorsTitle: "Find Best Doctors",
    doctorsSubtitle: "Connect with trusted healthcare professionals",
  },

  hi: {
    // Sidebar & Navigation
    dashboard: "डैशबोर्ड",
    bmiCalculator: "बीएमआई कैलकुलेटर",
    calories: "भोजन और कैलोरी",
    journey: "15-दिवसीय यात्रा",
    cycle: "साइकिल ट्रैकर",
    chat: "एआई न्यूट्रिशनिस्ट",
    aiChat: "एआई न्यूट्रिशनिस्ट",
    wellness: "स्वस्थ विचार",
    doctors: "डॉक्टर",
    profile: "प्रोफ़ाइल",
    settings: "सेटिंग्स",
    logout: "लॉगआउट",

    // Header & User dropdown
    profile2: "प्रोफ़ाइल",
    settings2: "सेटिंग्स",
    logout2: "लॉगआउट",

    // Greetings & Dashboard
    greetingMorning: "सुप्रभात",
    greetingAfternoon: "शुभ दोपहर",
    greetingEvening: "शुभ संध्या",
    hereIsYourHealth: "यहाँ आज का आपका स्वास्थ्य सारांश है 💗",
    yourBMI: "आपका बीएमआई",
    dailyCalories: "दैनिक कैलोरी",
    waterIntake: "पानी का सेवन",
    glasses: "गिलास",
    kcal: "kcal",
    recommended: "लक्ष्य",
    weeklyActivity: "जलयोजन इतिहास",
    waterConsumption: "दैनिक पानी का सेवन (गिलास)",
    healthOverview: "स्वास्थ्य अवलोकन",
    healthOverviewDesc: "आप एक अच्छा संतुलन बनाए रख रहे हैं। जारी रखें!",
    viewDetails: "15-दिन की प्रगति देखें",
    aiDailyTip: "एआई दैनिक अंतर्दृष्टि",
    hydrate: "पानी पिएं!",
    good: "अच्छा",
    perfect: "बढ़िया!",
    overhydrated: "भरपूर पानी!",
    calculateYourBMI: "ट्रैकिंग शुरू करने के लिए अपना बीएमआई निकालें",
    setCalorieTarget: "अपना दैनिक कैलोरी लक्ष्य निर्धारित करें",
    quickActions: "त्वरित क्रियाएं",
    logMeal: "भोजन जोड़ें",
    addWater: "पानी जोड़ें",
    logWeight: "वजन दर्ज करें",
    askAI: "एआई से पूछें",
    consumed: "सेवन किया",
    target: "लक्ष्य",
    remaining: "शेष",
    startTrackingToday: "अपनी 15-दिवसीय यात्रा शुरू करने के लिए आज ही ट्रैक करें।",

    // Meals & Calories Page
    mealLog: "दैनिक भोजन लॉग",
    calorieCalculator: "कैलोरी कैलकुलेटर",
    calorieTitle: "भोजन और कैलोरी ट्रैकिंग",
    calorieSubtitle: "भोजन ट्रैक करें, लक्ष्य निकालें और एआई पोषण विवरण प्राप्त करें",
    noMealsLoggedToday: "आज अभी तक कोई भोजन दर्ज नहीं किया गया।",
    dontKnowCalories: "कैलोरी नहीं पता? एआई से पूछें",
    addMealBtn: "+ भोजन जोड़ें",
    foodName: "भोजन का नाम",
    quantity: "मात्रा / भाग",
    estimatedCalories: "अनुमानित कैलोरी",
    protein: "प्रोटीन (g)",
    carbs: "कार्ब्स (g)",
    fat: "वसा (g)",
    mealType: "भोजन का प्रकार",
    breakfast: "नाश्ता",
    lunch: "दोपहर का भोजन",
    dinner: "रात का भोजन",
    snack: "स्नैक्स",
    saveMeal: "भोजन सहेजें",
    deleteMeal: "हटाएं",
    saveTargetBtn: "दैनिक लक्ष्य सहेजें",
    enterDetails: "विवरण दर्ज करें",
    age: "आयु",
    gender: "लिंग",
    selectGender: "लिंग चुनें",
    male: "पुरुष",
    female: "महिला",
    others: "अन्य",
    activityLevel: "गतिविधि स्तर",
    selectActivity: "गतिविधि स्तर चुनें",
    sedentary: "निष्क्रिय (कम या कोई व्यायाम नहीं)",
    light: "हल्का (1-3 दिन/सप्ताह)",
    moderate: "मध्यम (3-5 दिन/सप्ताह)",
    active: "सक्रिय (6-7 दिन/सप्ताह)",
    veryActive: "बहुत सक्रिय (तीव्र व्यायाम)",
    goal: "स्वास्थ्य लक्ष्य",
    loseWeight: "वजन घटाएं",
    maintainWeight: "वजन बनाए रखें",
    gainWeight: "वजन बढ़ाएं",
    estimatedDailyNeeds: "अनुमानित दैनिक कैलोरी आवश्यकता",
    bmr: "बेसल मेटाबॉलिक रेट (BMR)",
    tdee: "अनुमानित रखरखाव (TDEE)",
    calorieDisclaimer: "अनुमानित दैनिक कैलोरी आवश्यकता मिफ्लिन-सेंट जियोर दिशानिर्देशों पर आधारित है।",

    // BMI Page
    bmiTitle: "बीएमआई कैलकुलेटर",
    bmiSubtitle: "व्यक्तिगत सुझावों के साथ अपने बॉडी मास इंडेक्स की जांच करें",
    enterYourDetails: "अपना विवरण दर्ज करें",
    heightWeightForBMI: "बीएमआई गणना के लिए ऊंचाई और वजन",
    heightCm: "ऊंचाई (सेमी)",
    weightKg: "वजन (किग्रा)",
    calculateBMI: "बीएमआई कैलकुलेट करें",
    saveToProfile: "प्रोफ़ाइल और डैशबोर्ड में सहेजें",
    bmiCategories: "बीएमआई श्रेणियां",
    underweight: "कम वजन",
    normal: "सामान्य",
    overweight: "अधिक वजन",
    obese: "मोटापा",
    yourBMIResult: "आपका बीएमआई परिणाम",
    aiSuggestion: "एआई सुझाव",
    maintainBalanced: "संतुलित आहार लें और नियमित व्यायाम करें।",
    underweightSuggestion: "आपका वजन कम है। पौष्टिक खाद्य पदार्थों और स्वस्थ कैलोरी पर ध्यान दें।",
    normalSuggestion: "आप एक स्वस्थ सीमा में हैं! संतुलित आहार और नियमित व्यायाम बनाए रखें।",
    overweightSuggestion: "सचेत भोजन, साबुत अनाज और 30 मिनट की दैनिक गतिविधि पर ध्यान दें।",
    obeseSuggestion: "लगातार संतुलित पोषण, जलयोजन और स्वास्थ्य पेशेवर से परामर्श को प्राथमिकता दें।",
    bmiDisclaimer: "बीएमआई एक स्क्रीनिंग माप है और सीधे शरीर की चर्बी या समग्र स्वास्थ्य को नहीं मापता है।",

    // AI Chat
    chatTitle: "एआई पोषण साथी",
    chatSubtitle: "बुद्धिमान भोजन विश्लेषण, पोषण विवरण और आहार सलाह",
    chatPlaceholder: "व्यंजनों के बारे में पूछें, भोजन का नाम लिखें या फोटो अपलोड करें...",
    isHealthy: "क्या यह स्वस्थ है?",
    estimateCaloriesChip: "कैलोरी का अनुमान",
    nutritionTips: "पोषण सुझाव",
    saveToCalorieLog: "कैलोरी लॉग में सहेजें",
    imageLoaded: "छवि लोड हुई",
    readyForAnalysis: "पोषण स्कैन के लिए तैयार...",
    scanningMeal: "एआई के साथ भोजन स्कैन हो रहा है...",
    aiEstimatedNotice: "अनुमानित कैलोरी। वास्तविक मूल्य भाग, सामग्री और तैयारी पर निर्भर करते हैं।",

    // 15-Day Health Journey
    journeyTitle: "मेरी स्वास्थ्य यात्रा",
    journeySubtitle: "पिछले 15 दिनों की आपकी स्वास्थ्य और कल्याण प्रगति।",
    startingWeight: "प्रारंभिक वजन",
    currentWeight: "वर्तमान वजन",
    goalWeight: "लक्ष्य वजन",
    weightChange: "वजन परिवर्तन",
    avgCalories: "औसत कैलोरी",
    avgWater: "औसत पानी",
    weightTrend: "वजन प्रवृत्ति (किग्रा)",
    calorieTrend: "कैलोरी सेवन बनाम लक्ष्य",
    waterTrend: "पानी का सेवन (गिलास)",
    goalProgress: "लक्ष्य प्रगति",
    logNewWeight: "+ नया वजन दर्ज करें",

    // Women's Cycle Tracker
    cycleTitle: "महिला स्वास्थ्य और साइकिल ट्रैकर",
    cycleSubtitle: "साइकिल पूर्वानुमान और व्यक्तिगत कल्याण मार्गदर्शन।",
    periodStartedToday: "माहवारी आज शुरू हुई 🩸",
    currentPhase: "वर्तमान चरण",
    cycleDay: "साइकिल दिन",
    estimatedNextPeriod: "अनुमानित अगली माहवारी",
    estimatedFertileWindow: "अनुमानित उपजाऊ दिन",
    estimatedOvulation: "अनुमानित ओव्यूलेशन",
    menstrualPhase: "मासिक धर्म चरण",
    follicularPhase: "फॉलिक्युलर चरण",
    ovulationPhase: "ओव्यूलेशन चरण",
    lutealPhase: "ल्यूटियल चरण",
    cycleDisclaimer: "सभी चक्र और प्रजनन तिथियां कैलेंडर अनुमान हैं और चिकित्सीय गारंटी नहीं हैं।",
    cycleNutritionTips: "चरण पोषण सुझाव",

    // Nutrition & Wellness Library
    wellnessTitle: "पोषण और कल्याण पुस्तकालय",
    wellnessSubtitle: "प्रमाणित आहार योजनाएं, व्यावहारिक भोजन विचार और जीवनशैली गाइड",
    dietPlansTab: "आहार योजनाएं",
    mealIdeasTab: "भोजन के विचार",
    articlesTab: "कल्याण गाइड",
    readGuide: "गाइड पढ़ें",

    // Profile Page
    profileTitle: "प्रोफ़ाइल और कल्याण",
    profileSubtitle: "अपनी व्यक्तिगत स्वास्थ्य जानकारी प्रबंधित करें",
    editProfile: "प्रोफ़ाइल संपादित करें",
    saveChanges: "परिवर्तन सहेजें",
    healthInformation: "स्वास्थ्य मेट्रिक्स",
    height: "ऊंचाई",
    weight: "वजन",
    bloodType: "रक्त समूह",
    city: "शहर / स्थान",
    namePlaceholder: "अपना नाम दर्ज करें",
    emailPlaceholder: "आपका ईमेल",
    phonePlaceholder: "फ़ोन नंबर दर्ज करें",
    locationPlaceholder: "अपना शहर दर्ज करें",

    // Settings Page
    settingsTitle: "सेटिंग्स",
    settingsSubtitle: "अपनी ऐप प्राथमिकताएं प्रबंधित करें",
    preferences: "प्राथमिकताएं",
    darkMode: "डार्क मोड",
    darkModeDesc: "लाइट और डार्क थीम के बीच स्विच करें",
    language: "भाषा",
    languageDesc: "हिन्दी (भारत)",
    change: "बदलें",
    security: "सुरक्षा",
    changePassword: "पासवर्ड बदलें",
    dangerZone: "खतरा क्षेत्र",
    dangerZoneDesc: "एक बार आपका खाता हटाने के बाद, कोई वापसी नहीं है। कृपया सुनिश्चित करें।",
    deleteAccount: "खाता हटाएं",
    changePasswordTitle: "पासवर्ड बदलें",
    changePasswordSubtitle: "अपना खाता पासवर्ड अपडेट करें",
    currentPassword: "वर्तमान पासवर्ड",
    currentPasswordPlaceholder: "वर्तमान पासवर्ड दर्ज करें",
    newPassword: "नया पासवर्ड",
    newPasswordPlaceholder: "नया पासवर्ड दर्ज करें (न्यूनतम 6 अक्षर)",
    confirmPassword: "नया पासवर्ड की पुष्टि करें",
    confirmPasswordPlaceholder: "नया पासवर्ड फिर से दर्ज करें",
    updatePasswordBtn: "पासवर्ड अपडेट करें",
    updating: "अपडेट हो रहा है...",
    cancel: "रद्द करें",
    passwordUpdatedSuccess: "पासवर्ड सफलतापूर्वक अपडेट किया गया!",
    deleteConfirmTitle: "खाता स्थायी रूप से हटाएं?",
    deleteConfirmDesc: "यह क्रिया स्थायी है। आपकी प्रोफ़ाइल, स्वास्थ्य मेट्रिक्स और भोजन इतिहास मिटा दिए जाएंगे।",
    deleteConfirmPrompt: "पुष्टि के लिए अपना पासवर्ड दर्ज करें:",
    deletePasswordPlaceholder: "पुष्टि के लिए अपना पासवर्ड दर्ज करें",
    confirmDeleteBtn: "खाता स्थायी रूप से हटाएं",
    deleting: "हटाया जा रहा है...",

    // Errors & Auth
    userNotFound: "कोई प्रमाणित उपयोगकर्ता नहीं मिला।",
    notPasswordUser: "पासवर्ड परिवर्तन केवल ईमेल/पासवर्ड खातों के लिए उपलब्ध है।",
    enterCurrentPassword: "कृपया अपना वर्तमान पासवर्ड दर्ज करें।",
    passwordTooShort: "नया पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।",
    passwordsDoNotMatch: "नए पासवर्ड मेल नहीं खाते।",
    wrongPassword: "दर्ज किया गया वर्तमान पासवर्ड गलत है।",
    recentLoginRequired: "इस क्रिया के लिए हालिया प्रमाणीकरण आवश्यक है। कृपया अपना वर्तमान पासवर्ड सत्यापित करें।",
    tooManyAttempts: "बहुत अधिक प्रयास। कृपया बाद में पुनः प्रयास करें।",
    welcomeBack: "वापस स्वागत है",
    signInToContinue: "अपनी स्वास्थ्य यात्रा जारी रखने के लिए साइन इन करें",
    rememberMe: "मुझे याद रखें",
    forgotPassword: "पासवर्ड भूल गए?",
    login: "लॉगिन",
    orContinueWith: "या इसके साथ जारी रखें",
    noAccount: "खाता नहीं है?",
    signUp: "साइन अप",
    createAccount: "खाता बनाएं",
    joinHealthJourney: "आज अपनी स्वास्थ्य यात्रा शुरू करें",
    fullName: "पूरा नाम",
    orSignUpWith: "या इसके साथ साइन अप करें",
    alreadyHaveAccount: "पहले से खाता है?",
    agreeToTerms: "मैं नियम और शर्तों से सहमत हूं",
    viewProfile: "प्रोफ़ाइल देखें",
    doctorsTitle: "सर्वश्रेष्ठ डॉक्टर खोजें",
    doctorsSubtitle: "विश्वसनीय स्वास्थ्य पेशेवरों से जुड़ें",
  },
}

type Lang = "en" | "hi"
type TranslationKey = keyof typeof translations.en

interface LanguageContextType {
  language: Lang
  setLanguage: (lang: Lang) => void
  t: (key: TranslationKey, fallback?: string) => string
}

const LanguageContext = createContext<LanguageContextType | null>(null)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Lang>("en")

  useEffect(() => {
    try {
      const saved = localStorage.getItem("medinutri_language") as Lang
      if (saved === "en" || saved === "hi") {
        setLanguageState(saved)
      }
    } catch {}
  }, [])

  const setLanguage = (lang: Lang) => {
    setLanguageState(lang)
    try {
      localStorage.setItem("medinutri_language", lang)
    } catch {}
  }

  const t = (key: TranslationKey, fallback?: string): string => {
    return translations[language][key] ?? fallback ?? key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage(): LanguageContextType {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider")
  return ctx
}